import { type UpdateFn, updateRegistrering, updateUferdigRegistrering } from '@app/redux/api/registreringer/queries';
import type { DraftRegistrering, Overstyringer, Svarbrev } from '@app/redux/api/registreringer/types';

// All drafts
export const updateDrafts = (id: string, update: UpdateFn<DraftRegistrering>): (() => void) => {
  const patchResult = updateRegistrering(id, (draft) => (draft.finished === null ? update(draft) : draft));
  const unfinishedPatchResult = updateUferdigRegistrering(id, update);

  return () => {
    patchResult.undo();
    unfinishedPatchResult.undo();
  };
};

export interface PartialDraftRegistrering
  extends Partial<Omit<DraftRegistrering, 'overstyringer' | 'svarbrev' | 'uploadedDocuments'>> {
  overstyringer?: Partial<Overstyringer>;
  svarbrev?: Partial<Svarbrev>;
  uploadedDocuments?: Partial<DraftRegistrering['uploadedDocuments']>;
}

/** Whether `response` was generated by the server *before* whatever is currently cached in
 * `draft` was last written. `modified` is set purely server-side - nothing in this codebase
 * writes it optimistically - so it can be trusted as a monotonic marker of how current a
 * response is, even when responses from different mutations for the same registrering arrive
 * out of order (e.g. two rapid calls to the same mutation, whose responses then resolve in the
 * opposite order). `undefined` (a response that happens not to carry `modified`) is treated as
 * "not stale", preserving the previous always-apply behavior. */
export const isStaleResponse = (response: { modified?: string }, draft: DraftRegistrering): boolean =>
  response.modified !== undefined && response.modified < draft.modified;

export const pessimisticUpdate = (id: string, response: PartialDraftRegistrering = {}) =>
  updateDrafts(id, (draft) => {
    if (isStaleResponse(response, draft)) {
      return draft;
    }

    return {
      ...draft,
      ...response,
      overstyringer: { ...draft.overstyringer, ...response.overstyringer },
      svarbrev: { ...draft.svarbrev, ...response.svarbrev },
      uploadedDocuments: { ...draft.uploadedDocuments, ...response.uploadedDocuments },
    };
  });
