ingresses:
  - https://kabin.intern.dev.nav.no
  - https://kabin.ansatt.dev.nav.no
tenant: trygdeetaten.no
roles:
  - 7ad08bfe-68d4-4c84-bddd-82d8894fb36e # KABAL_OPPGAVESTYRING_ALLE_ENHETER
  - 14d756b4-d014-419a-a5bc-b8f9e31ce248 # KABAL_ADMIN
